trigger:
  - main

pool:
  name: Default

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      cd app
      npm install
    displayName: 'Install dependencies in app folder'

  - script: |
      cd app
      powershell -Command "Compress-Archive -Path * -DestinationPath $(Build.ArtifactStagingDirectory)\app.zip"
    displayName: 'Create ZIP from app folder'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publish app.zip as artifact'
