
trigger:
  - main

pool:
  name: Default

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      cd app
      npm install
    displayName: 'Install dependencies'

  - script: |
      cd app
      npm start
    displayName: 'Start application'

  - script: |
      echo "Publishing contents of $(System.DefaultWorkingDirectory)/app"
    displayName: 'Log artifact path'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(System.DefaultWorkingDirectory)/app'
      artifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publish Build Artifacts'
    condition: succeeded()
