
trigger:
  - main

pool:
  name: Default

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      cd app
      npm install
    displayName: 'Install dependencies'

  - script: |
      cd app
      node app.js
    displayName: 'Start application using app.js'

  - script: |
      dir $(Build.SourcesDirectory)/app
    displayName: 'List files in app folder'
