
trigger:
  - main

pool:
  name: Default

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'Install dependencies'

  - script: |
      start /B node app.js
    displayName: 'Start application using app.js in background'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/app'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
      replaceExistingArchive: true
    displayName: 'Archive app folder to app.zip'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publish Build Artifacts'
    condition: succeeded()

  - task: AzureRmWebAppDeployment@5
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'AzureConnection-bootcamp'
      appType: 'webApp'
      WebAppName: 'bootcamp-cicd-demo-app'
      deployToSlotOrASE: true
      ResourceGroupName: 'bootcamp-rg'
      SlotName: 'staging'
      packageForLinux: '$(System.DefaultWorkingDirectory)/drop/app.zip'
      enableCustomDeployment: true
      DeploymentType: 'webDeploy'
    displayName: 'Deploy to Azure App Service staging slot'
