trigger:
- main   # replace with your actual default branch

pool:
  name: 'Default'   # or your self-hosted agent pool name

variables:
  azureServiceConnection: 'AzureBootcampConnection'   # your service connection name
  appServiceName: 'bootcamp-cicd-demo-app'            # your App Service name

stages:
# -------------------
# 1. Build Stage
# -------------------
- stage: Build
  displayName: 'Build and Package'
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-latest'   # or your agent pool
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    - script: npm install
      displayName: 'Install npm packages'

    - script: npm test
      displayName: 'Run tests'

    # 👇 Adjust this path if your app.js lives in /src
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)/src'
        includeRootFolder: false
        archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
        replaceExistingArchive: true
      displayName: 'Archive app files'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/app.zip'
        ArtifactName: 'drop'
        publishLocation: 'Container'
      displayName: 'Publish build artifact'

# -------------------
# 2. Deploy Stage
# -------------------
- stage: Deploy
  displayName: 'Deploy to Azure App Service'
  dependsOn: Build
  jobs:
  - job: DeployJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifactName: 'drop'
        targetPath: '$(System.DefaultWorkingDirectory)'
      displayName: 'Download build artifact'

    - task: AzureWebApp@1
      inputs:
        azureSubscription: '$(azureServiceConnection)'
        appName: '$(appServiceName)'
        package: '$(System.DefaultWorkingDirectory)/**/*.zip'
      displayName: 'Deploy to Azure App Service'
