trigger:
- main   # or your default branch

pool:
  vmImage: 'windows-latest'

variables:
  # Bootcamp-friendly placeholders
  azureServiceConnection: 'AzureBootcampConnection'   # create this in Project Settings > Service connections
  appServiceName: 'bootcamp-cicd-demo-app'            # replace with your App Service name

steps:
# 1. Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# 2. Install dependencies
- script: |
    npm install
  displayName: 'Install npm packages'

# 3. Run tests (optional)
- script: |
    npm test
  displayName: 'Run tests'

# 4. Archive the app (package.json + app.js + node_modules)
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true
  displayName: 'Archive app files'

# 5. Publish artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/app.zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish build artifact'

# 6. Deploy to Azure App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureServiceConnection)'
    appName: '$(appServiceName)'
    package: '$(Pipeline.Workspace)/drop/app.zip'
  displayName: 'Deploy to Azure App Service'
